detectors:
  onnx:
    type: onnx

model:
  model_type: yolo-generic
  path: /config/model_cache/yolov9-t-320.onnx
  labelmap_path: /config/labelmap/coco-80.txt
  input_tensor: nchw
  input_pixel_format: rgb
  input_dtype: float
  width: 320
  height: 320

go2rtc:
  streams:
    cam1:
      - rtsp://admin:admin123@192.168.85.112:554/Streaming/Channels/101
      - "ffmpeg:cam1#audio=opus"
  webrtc:
    candidates:
      - 192.168.85.203:8555

mqtt:
  enabled: true
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate

cameras:
  cam1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin123@192.168.85.112:554/Streaming/Channels/102
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://admin:admin123@192.168.85.112:554/Streaming/Channels/101
          input_args: preset-rtsp-generic
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
        - dog
        - cat
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
    mqtt:
      enabled: true
      crop: true
      quality: 90
      height: 500
    snapshots:
      enabled: true
      clean_copy: true
      quality: 95

record:
  enabled: true
  retain:
    days: 7
    mode: motion

snapshots:
  enabled: true
  clean_copy: true
  quality: 95
