version: "3.8"

services:
  frigate-intelligence:
    build: .
    container_name: frigate-intelligence
    restart: unless-stopped
    ports:
      - "8088:8000"
    volumes:
      - /opt/frigate/config:/opt/frigate/config
    env_file:
      - .env
    networks:
      - frigate-net

  frigate-web-panel:
    build:
      context: ./frigate-web-panel
      dockerfile: Dockerfile
    container_name: frigate-web-panel
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.85.202:8088
      - NEXT_PUBLIC_FRIGATE_URL=http://192.168.85.203:5000
    depends_on:
      - frigate-intelligence
    networks:
      - frigate-net

networks:
  frigate-net:
    driver: bridge
